#!/usr/bin/env perl
use v5.34;
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use GobanFTP::CLI;

binmode STDOUT, ':unix:utf8';
binmode STDERR, ':unix:utf8';

exit GobanFTP::CLI->run(@ARGV);
